finish the build process for erl-service

diff --git a/orbs/erl-service/orb.yml b/orbs/erl-service/orb.yml
--- a/orbs/erl-service/orb.yml
+++ b/orbs/erl-service/orb.yml
@@ -57,15 +57,23 @@ jobs:
       - run:
           name: "Build the project"
           command: |
+            # We need two versions of the release tarbalL: one to be archived
+            # as artifact named after the project and Git hash, and one with a
+            # fixed name to be used by the docker/build_image step. We could
+            # use a Docker build argument to point to the right tarball, but
+            # it would require having a way to pass them to the corresponding
+            # CircleCI command. Let us keep it simple for the time being.
             make release
-            tarball=$CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz
+            tarball=./release/$CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz
             if [ ! -f $tarball ]; then
               echo "missing release tarball at $tarball" >&2
               exit 1
             fi
-            cp $tarball service.tar.gz
-            mkdir ./release
-            mv $tarball ./release
+            tarball=./release/service.tar.gz
+            if [ ! -f $tarball ]; then
+              echo "missing release tarball at $tarball" >&2
+              exit 1
+            fi
       - store_artifacts:
           path: "./release"
       - docker/setup
